#!/bin/bash
#PBS -P c37
#PBS -q normal
#PBS -j oe
#PBS -l walltime=00:01:00,mem=50GB
#PBS -l wd
#PBS -l ncpus=288
#

module load openmpi/4.0.1
mpirun -n 256 ./TaskB-1  ../testcases/input_testcase_1000 ../testcases/output
mpirun -n 256 ./TaskB-2  ../testcases/input_testcase_1000 ../testcases/output