#!/bin/bash
#PBS -P c37
#PBS -q normal
#PBS -j oe
#PBS -l walltime=00:01:00,mem=1GB
#PBS -l wd
#PBS -l ncpus=96
#

module load openmpi/4.0.1
./Task4A-1 64 ../testcases/input_testcase_1000 ../testcases_output
./Task4A-2 64 ../testcases/input_testcase_1000 ../testcases_output